#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidApp.Resource", IsApplication=true)]

namespace AndroidApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int dinmor = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int hamburgericonny1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int KapacitetStatusIngenSiddepladser = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int KapacitetStatusMasserafplads = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int KapacitetStatusNaesteningensiddepladser = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int KapacitetStatusOverfyldt = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int mad = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int smiley2 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int smiley3 = 2130837513;
			
			// aapt resource value: 0x7f02003b
			public const int abc_scrubber_primary_mtrl_alpha = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int abc_scrubber_track_mtrl_alpha = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int abc_seekbar_thumb_material = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int abc_seekbar_track_material = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int abc_spinner_mtrl_am_alpha = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int abc_spinner_textfield_background_material = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int abc_switch_thumb_material = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int abc_switch_track_mtrl_alpha = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int abc_tab_indicator_material = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int abc_tab_indicator_mtrl_alpha = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int abc_text_cursor_material = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int abc_textfield_activated_mtrl_alpha = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int abc_textfield_default_mtrl_alpha = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int abc_textfield_search_activated_mtrl_alpha = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int abc_textfield_search_default_mtrl_alpha = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int abc_textfield_search_material = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int design_fab_background = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int design_snackbar_background = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int dinmor = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int hamburgericonny1 = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int HomeIkon = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int ic_audiotrack = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int ic_audiotrack_light = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int ic_bluetooth_grey = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int ic_bluetooth_white = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int ic_cast_dark = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int ic_cast_disabled_light = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int ic_cast_grey = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int ic_cast_light = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int ic_cast_off_light = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int ic_cast_on_0_light = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int ic_cast_on_1_light = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int ic_cast_on_2_light = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int ic_cast_on_light = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int ic_cast_white = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int ic_close_dark = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int ic_close_light = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int ic_collapse = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int ic_collapse_00000 = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int ic_collapse_00001 = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int ic_collapse_00002 = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int ic_collapse_00003 = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int ic_collapse_00004 = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int ic_collapse_00005 = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int ic_collapse_00006 = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int ic_collapse_00007 = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int ic_collapse_00008 = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int ic_collapse_00009 = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int ic_collapse_00010 = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int ic_collapse_00011 = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int ic_collapse_00012 = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int ic_collapse_00013 = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int ic_collapse_00014 = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int ic_collapse_00015 = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int ic_expand = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int ic_expand_00000 = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int ic_expand_00001 = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int ic_expand_00002 = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int ic_expand_00003 = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int ic_expand_00004 = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int ic_expand_00005 = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int ic_expand_00006 = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int ic_expand_00007 = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int ic_expand_00008 = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int ic_expand_00009 = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int ic_expand_00010 = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public const int ic_expand_00011 = 2130837629;
			
			// aapt resource value: 0x7f02007e
			public const int ic_expand_00012 = 2130837630;
			
			// aapt resource value: 0x7f02007f
			public const int ic_expand_00013 = 2130837631;
			
			// aapt resource value: 0x7f020080
			public const int ic_expand_00014 = 2130837632;
			
			// aapt resource value: 0x7f020081
			public const int ic_expand_00015 = 2130837633;
			
			// aapt resource value: 0x7f020082
			public const int ic_media_pause = 2130837634;
			
			// aapt resource value: 0x7f020083
			public const int ic_media_play = 2130837635;
			
			// aapt resource value: 0x7f020084
			public const int ic_media_route_disabled_mono_dark = 2130837636;
			
			// aapt resource value: 0x7f020085
			public const int ic_media_route_off_mono_dark = 2130837637;
			
			// aapt resource value: 0x7f020086
			public const int ic_media_route_on_0_mono_dark = 2130837638;
			
			// aapt resource value: 0x7f020087
			public const int ic_media_route_on_1_mono_dark = 2130837639;
			
			// aapt resource value: 0x7f020088
			public const int ic_media_route_on_2_mono_dark = 2130837640;
			
			// aapt resource value: 0x7f020089
			public const int ic_media_route_on_mono_dark = 2130837641;
			
			// aapt resource value: 0x7f02008a
			public const int ic_pause_dark = 2130837642;
			
			// aapt resource value: 0x7f02008b
			public const int ic_pause_light = 2130837643;
			
			// aapt resource value: 0x7f02008c
			public const int ic_play_dark = 2130837644;
			
			// aapt resource value: 0x7f02008d
			public const int ic_play_light = 2130837645;
			
			// aapt resource value: 0x7f02008e
			public const int ic_speaker_dark = 2130837646;
			
			// aapt resource value: 0x7f02008f
			public const int ic_speaker_group_dark = 2130837647;
			
			// aapt resource value: 0x7f020090
			public const int ic_speaker_group_light = 2130837648;
			
			// aapt resource value: 0x7f020091
			public const int ic_speaker_light = 2130837649;
			
			// aapt resource value: 0x7f020092
			public const int ic_tv_dark = 2130837650;
			
			// aapt resource value: 0x7f020093
			public const int ic_tv_light = 2130837651;
			
			// aapt resource value: 0x7f020094
			public const int Icon = 2130837652;
			
			// aapt resource value: 0x7f020095
			public const int KapacitetStatusIngenSiddepladser = 2130837653;
			
			// aapt resource value: 0x7f020096
			public const int KapacitetStatusMasserafplads = 2130837654;
			
			// aapt resource value: 0x7f020097
			public const int KapacitetStatusNaesteningensiddepladser = 2130837655;
			
			// aapt resource value: 0x7f020098
			public const int KapacitetStatusOverfyldt = 2130837656;
			
			// aapt resource value: 0x7f020099
			public const int mad = 2130837657;
			
			// aapt resource value: 0x7f02009a
			public const int mr_dialog_material_background_dark = 2130837658;
			
			// aapt resource value: 0x7f02009b
			public const int mr_dialog_material_background_light = 2130837659;
			
			// aapt resource value: 0x7f02009c
			public const int mr_ic_audiotrack_light = 2130837660;
			
			// aapt resource value: 0x7f02009d
			public const int mr_ic_cast_dark = 2130837661;
			
			// aapt resource value: 0x7f02009e
			public const int mr_ic_cast_light = 2130837662;
			
			// aapt resource value: 0x7f02009f
			public const int mr_ic_close_dark = 2130837663;
			
			// aapt resource value: 0x7f0200a0
			public const int mr_ic_close_light = 2130837664;
			
			// aapt resource value: 0x7f0200a1
			public const int mr_ic_media_route_connecting_mono_dark = 2130837665;
			
			// aapt resource value: 0x7f0200a2
			public const int mr_ic_media_route_connecting_mono_light = 2130837666;
			
			// aapt resource value: 0x7f0200a3
			public const int mr_ic_media_route_mono_dark = 2130837667;
			
			// aapt resource value: 0x7f0200a4
			public const int mr_ic_media_route_mono_light = 2130837668;
			
			// aapt resource value: 0x7f0200a5
			public const int mr_ic_pause_dark = 2130837669;
			
			// aapt resource value: 0x7f0200a6
			public const int mr_ic_pause_light = 2130837670;
			
			// aapt resource value: 0x7f0200a7
			public const int mr_ic_play_dark = 2130837671;
			
			// aapt resource value: 0x7f0200a8
			public const int mr_ic_play_light = 2130837672;
			
			// aapt resource value: 0x7f0200ab
			public const int notification_template_icon_bg = 2130837675;
			
			// aapt resource value: 0x7f0200a9
			public const int smiley2 = 2130837673;
			
			// aapt resource value: 0x7f0200aa
			public const int smiley3 = 2130837674;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0700a4
			public const int BusList = 2131165348;
			
			// aapt resource value: 0x7f07007a
			public const int Fuckdigtekst = 2131165306;
			
			// aapt resource value: 0x7f0700a3
			public const int HomeButton = 2131165347;
			
			// aapt resource value: 0x7f07007b
			public const int KnapAendrer = 2131165307;
			
			// aapt resource value: 0x7f050007
			public const int ResultButton = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int StoppestedInput = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int favButton = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int imageButton1 = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int nytid = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int textView1 = 2131034115;
			
			// aapt resource value: 0x7f070002
			public const int action_bar_spinner = 2131165186;
			
			// aapt resource value: 0x7f07003b
			public const int action_bar_subtitle = 2131165243;
			
			// aapt resource value: 0x7f07003a
			public const int action_bar_title = 2131165242;
			
			// aapt resource value: 0x7f07005b
			public const int action_context_bar = 2131165275;
			
			// aapt resource value: 0x7f070099
			public const int action_divider = 2131165337;
			
			// aapt resource value: 0x7f070003
			public const int action_menu_divider = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int action_menu_presenter = 2131165188;
			
			// aapt resource value: 0x7f070057
			public const int action_mode_bar = 2131165271;
			
			// aapt resource value: 0x7f070056
			public const int action_mode_bar_stub = 2131165270;
			
			// aapt resource value: 0x7f07003c
			public const int action_mode_close_button = 2131165244;
			
			// aapt resource value: 0x7f07003d
			public const int activity_chooser_view_content = 2131165245;
			
			// aapt resource value: 0x7f070049
			public const int alertTitle = 2131165257;
			
			// aapt resource value: 0x7f07001e
			public const int always = 2131165214;
			
			// aapt resource value: 0x7f07001b
			public const int beginning = 2131165211;
			
			// aapt resource value: 0x7f07002a
			public const int bottom = 2131165226;
			
			// aapt resource value: 0x7f070044
			public const int buttonPanel = 2131165252;
			
			// aapt resource value: 0x7f070096
			public const int cancel_action = 2131165334;
			
			// aapt resource value: 0x7f07002b
			public const int center = 2131165227;
			
			// aapt resource value: 0x7f07002c
			public const int center_horizontal = 2131165228;
			
			// aapt resource value: 0x7f07002d
			public const int center_vertical = 2131165229;
			
			// aapt resource value: 0x7f070052
			public const int checkbox = 2131165266;
			
			// aapt resource value: 0x7f07009c
			public const int chronometer = 2131165340;
			
			// aapt resource value: 0x7f070033
			public const int clip_horizontal = 2131165235;
			
			// aapt resource value: 0x7f070034
			public const int clip_vertical = 2131165236;
			
			// aapt resource value: 0x7f07001f
			public const int collapseActionView = 2131165215;
			
			// aapt resource value: 0x7f07004a
			public const int contentPanel = 2131165258;
			
			// aapt resource value: 0x7f070050
			public const int custom = 2131165264;
			
			// aapt resource value: 0x7f07004f
			public const int customPanel = 2131165263;
			
			// aapt resource value: 0x7f070058
			public const int decor_content_parent = 2131165272;
			
			// aapt resource value: 0x7f070040
			public const int default_activity_button = 2131165248;
			
			// aapt resource value: 0x7f07006a
			public const int design_bottom_sheet = 2131165290;
			
			// aapt resource value: 0x7f070071
			public const int design_menu_item_action_area = 2131165297;
			
			// aapt resource value: 0x7f070070
			public const int design_menu_item_action_area_stub = 2131165296;
			
			// aapt resource value: 0x7f07006f
			public const int design_menu_item_text = 2131165295;
			
			// aapt resource value: 0x7f07006e
			public const int design_navigation_view = 2131165294;
			
			// aapt resource value: 0x7f07000e
			public const int disableHome = 2131165198;
			
			// aapt resource value: 0x7f07005c
			public const int edit_query = 2131165276;
			
			// aapt resource value: 0x7f07001c
			public const int end = 2131165212;
			
			// aapt resource value: 0x7f0700a1
			public const int end_padder = 2131165345;
			
			// aapt resource value: 0x7f070023
			public const int enterAlways = 2131165219;
			
			// aapt resource value: 0x7f070024
			public const int enterAlwaysCollapsed = 2131165220;
			
			// aapt resource value: 0x7f070025
			public const int exitUntilCollapsed = 2131165221;
			
			// aapt resource value: 0x7f07003e
			public const int expand_activities_button = 2131165246;
			
			// aapt resource value: 0x7f070051
			public const int expanded_menu = 2131165265;
			
			// aapt resource value: 0x7f070074
			public const int favButton = 2131165300;
			
			// aapt resource value: 0x7f070035
			public const int fill = 2131165237;
			
			// aapt resource value: 0x7f070036
			public const int fill_horizontal = 2131165238;
			
			// aapt resource value: 0x7f07002e
			public const int fill_vertical = 2131165230;
			
			// aapt resource value: 0x7f070038
			public const int @fixed = 2131165240;
			
			// aapt resource value: 0x7f070005
			public const int home = 2131165189;
			
			// aapt resource value: 0x7f07000f
			public const int homeAsUp = 2131165199;
			
			// aapt resource value: 0x7f070042
			public const int icon = 2131165250;
			
			// aapt resource value: 0x7f070020
			public const int ifRoom = 2131165216;
			
			// aapt resource value: 0x7f07003f
			public const int image = 2131165247;
			
			// aapt resource value: 0x7f070073
			public const int imageButton1 = 2131165299;
			
			// aapt resource value: 0x7f0700a0
			public const int info = 2131165344;
			
			// aapt resource value: 0x7f070000
			public const int item_touch_helper_previous_elevation = 2131165184;
			
			// aapt resource value: 0x7f07002f
			public const int left = 2131165231;
			
			// aapt resource value: 0x7f07009a
			public const int line1 = 2131165338;
			
			// aapt resource value: 0x7f07009e
			public const int line3 = 2131165342;
			
			// aapt resource value: 0x7f070072
			public const int linearLayout1 = 2131165298;
			
			// aapt resource value: 0x7f0700a2
			public const int linearLayout2 = 2131165346;
			
			// aapt resource value: 0x7f07000b
			public const int listMode = 2131165195;
			
			// aapt resource value: 0x7f070041
			public const int list_item = 2131165249;
			
			// aapt resource value: 0x7f070098
			public const int media_actions = 2131165336;
			
			// aapt resource value: 0x7f07001d
			public const int middle = 2131165213;
			
			// aapt resource value: 0x7f070037
			public const int mini = 2131165239;
			
			// aapt resource value: 0x7f070087
			public const int mr_art = 2131165319;
			
			// aapt resource value: 0x7f07007c
			public const int mr_chooser_list = 2131165308;
			
			// aapt resource value: 0x7f07007f
			public const int mr_chooser_route_desc = 2131165311;
			
			// aapt resource value: 0x7f07007d
			public const int mr_chooser_route_icon = 2131165309;
			
			// aapt resource value: 0x7f07007e
			public const int mr_chooser_route_name = 2131165310;
			
			// aapt resource value: 0x7f070084
			public const int mr_close = 2131165316;
			
			// aapt resource value: 0x7f07008a
			public const int mr_control_divider = 2131165322;
			
			// aapt resource value: 0x7f070090
			public const int mr_control_play_pause = 2131165328;
			
			// aapt resource value: 0x7f070093
			public const int mr_control_subtitle = 2131165331;
			
			// aapt resource value: 0x7f070092
			public const int mr_control_title = 2131165330;
			
			// aapt resource value: 0x7f070091
			public const int mr_control_title_container = 2131165329;
			
			// aapt resource value: 0x7f070085
			public const int mr_custom_control = 2131165317;
			
			// aapt resource value: 0x7f070086
			public const int mr_default_control = 2131165318;
			
			// aapt resource value: 0x7f070081
			public const int mr_dialog_area = 2131165313;
			
			// aapt resource value: 0x7f070080
			public const int mr_expandable_area = 2131165312;
			
			// aapt resource value: 0x7f070094
			public const int mr_group_expand_collapse = 2131165332;
			
			// aapt resource value: 0x7f070088
			public const int mr_media_main_control = 2131165320;
			
			// aapt resource value: 0x7f070083
			public const int mr_name = 2131165315;
			
			// aapt resource value: 0x7f070089
			public const int mr_playback_control = 2131165321;
			
			// aapt resource value: 0x7f070082
			public const int mr_title_bar = 2131165314;
			
			// aapt resource value: 0x7f07008b
			public const int mr_volume_control = 2131165323;
			
			// aapt resource value: 0x7f07008c
			public const int mr_volume_group_list = 2131165324;
			
			// aapt resource value: 0x7f07008e
			public const int mr_volume_item_icon = 2131165326;
			
			// aapt resource value: 0x7f07008f
			public const int mr_volume_slider = 2131165327;
			
			// aapt resource value: 0x7f070016
			public const int multiply = 2131165206;
			
			// aapt resource value: 0x7f07006d
			public const int navigation_header_container = 2131165293;
			
			// aapt resource value: 0x7f070021
			public const int never = 2131165217;
			
			// aapt resource value: 0x7f070010
			public const int none = 2131165200;
			
			// aapt resource value: 0x7f07000c
			public const int normal = 2131165196;
			
			// aapt resource value: 0x7f070078
			public const int nytid = 2131165304;
			
			// aapt resource value: 0x7f070028
			public const int parallax = 2131165224;
			
			// aapt resource value: 0x7f070046
			public const int parentPanel = 2131165254;
			
			// aapt resource value: 0x7f070029
			public const int pin = 2131165225;
			
			// aapt resource value: 0x7f070006
			public const int progress_circular = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int progress_horizontal = 2131165191;
			
			// aapt resource value: 0x7f070054
			public const int radio = 2131165268;
			
			// aapt resource value: 0x7f070030
			public const int right = 2131165232;
			
			// aapt resource value: 0x7f070017
			public const int screen = 2131165207;
			
			// aapt resource value: 0x7f070026
			public const int scroll = 2131165222;
			
			// aapt resource value: 0x7f07004e
			public const int scrollIndicatorDown = 2131165262;
			
			// aapt resource value: 0x7f07004b
			public const int scrollIndicatorUp = 2131165259;
			
			// aapt resource value: 0x7f07004c
			public const int scrollView = 2131165260;
			
			// aapt resource value: 0x7f070039
			public const int scrollable = 2131165241;
			
			// aapt resource value: 0x7f07005e
			public const int search_badge = 2131165278;
			
			// aapt resource value: 0x7f07005d
			public const int search_bar = 2131165277;
			
			// aapt resource value: 0x7f07005f
			public const int search_button = 2131165279;
			
			// aapt resource value: 0x7f070064
			public const int search_close_btn = 2131165284;
			
			// aapt resource value: 0x7f070060
			public const int search_edit_frame = 2131165280;
			
			// aapt resource value: 0x7f070066
			public const int search_go_btn = 2131165286;
			
			// aapt resource value: 0x7f070061
			public const int search_mag_icon = 2131165281;
			
			// aapt resource value: 0x7f070062
			public const int search_plate = 2131165282;
			
			// aapt resource value: 0x7f070063
			public const int search_src_text = 2131165283;
			
			// aapt resource value: 0x7f070067
			public const int search_voice_btn = 2131165287;
			
			// aapt resource value: 0x7f070068
			public const int select_dialog_listview = 2131165288;
			
			// aapt resource value: 0x7f070053
			public const int shortcut = 2131165267;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Results = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
